defaults:
  # username: postgres     password: 16034
  db_url: postgresql+psycopg2://postgres:16034@localhost:5432/postgres
  table_prefix: uber_   # optional prefix for staging tables
  batch_size: 5000

sources:
  - name: uber_trips
    file: data/UberDataset_validated.csv
    schema:
      start_date: datetime
      end_date: datetime
      category: str
      start: str
      stop: str
      miles: float
      purpose: str
    rules:
      - rule: "miles >= 0"
      - rule: "start_date <= end_date"